include "#!./gradlew -q composeApp:printConveyorConfig"
include "/stdlib/jdk/21/amazon.conf"

app {
    machines = [windows.amd64, linux.aarch64, linux.arm64, mac.aarch64]

    display-name = "Chirp"
    fsname = "chirp"
    description = "Chirp Chat Application"
    rdns-name = "com.leandrour.chirp"

    url-schemes = ["chirp"]

    inputs += "composeApp/build/libs/composeApp-desktop-*.jar"

    icons = "conveyorResources/logo.png"

    single-instance = true

    license = "MIT"
    updates = none

    jvm {
        main-class = "com.leandrour.chirp.MainKt"
        gui.main-class = "com.leandrour.chirp.MainKt"

        version = 21

        options = [
            "-Xmx2g",
            "--add-opens=java.base/sun.misc=ALL-UNNAMED",
            "--add-opens=java.base/java.nio=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt.wl=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED",
        ]

        modules = [
            java.desktop,
            java.logging,
            java.prefs,
            java.sql,
            jdk.unsupported
        ]
    }

    mac {
        info-plist {
            "com.apple.developer.associated-domains" = [
                "applinks:chirp.leandrour.com"
            ]
        }
    }

    windows.manifest.application.extensions = [
            {
                category = "windows.appUriHandler",
                host = "chirp.leandrour.com"
            }
        ]
}

windows {
    installer-type = "msix"

    start-menu = true
    desktop = true

    console = false

    certificate = "self-signed"
}

linux {
    installer-type = "deb"
    applications-menu = true

    desktop-file {
        Name = "Chirp"
        Type = "Application"
        Exec = "chirp %u"
        categories = ["Network", "Chat"]
        keywords = ["chat", "messaging", "chirp"]
        mime-types = ["x-scheme-handler/chirp"]
    }
}

conveyor {
    compatibility-level = 19
}